# Generated by Django 4.2.11 on 2025-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_partnerlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_picture/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
