# Generated by Django 4.2.11 on 2025-04-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_related_picture_delete_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ethnicity',
            new_name='FacultyRank',
        ),
        migrations.RenameField(
            model_name='facultyrank',
            old_name='ethnicityDescription',
            new_name='FacultyRankDescription',
        ),
        migrations.RenameField(
            model_name='facultyrank',
            old_name='ethnicityKey',
            new_name='FacultyRankKey',
        ),
    ]
