# Generated by Django 4.2.11 on 2025-04-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_ethnicity_facultyrank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_img/'),
        ),
    ]
