# Generated by Django 4.2.11 on 2025-04-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_advisory_calendar_plot_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
