# Generated by Django 4.2.11 on 2025-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_requirement_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
