# Generated by Django 4.2.11 on 2025-04-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_helpdeskmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestMember',
            new_name='TopContributor',
        ),
        migrations.DeleteModel(
            name='EventSchedule',
        ),
        migrations.AddField(
            model_name='progresstracking',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='progress_tracking_img/'),
        ),
    ]
