# Generated by Django 4.2.11 on 2025-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_bestmember_topcontributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id_picture', models.ImageField(blank=True, null=True, upload_to='candidate_pics/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('employment', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_number', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LineUp',
        ),
    ]
