# Generated by Django 4.2.11 on 2025-04-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_candidate_delete_lineup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
