# Generated by Django 4.2.11 on 2025-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorpost',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='sponsorpost_pics/'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='videopost_pics/'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_files/'),
        ),
    ]
